server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            use:
              type:
                headers: false
            trusted:
              packages: "com.example.paymentservice.dto"
            value:
              default:
                type: com.example.paymentservice.dto.OrderCreatedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

resilience4j:
  retry:
    instances:
      paymentGateway:
        max-attempts: 5
        wait-duration: 500ms

payment:
  gateway:
    timeout-simulation:
      enabled: ${PAYMENT_GATEWAY_TIMEOUT_SIMULATION_ENABLED:true}
      fail-attempts: ${PAYMENT_GATEWAY_TIMEOUT_SIMULATION_FAIL_ATTEMPTS:2}

